version: "3"

services:
  client:
    build: ../client
    volumes:
      - ../client:/sns/client
    ports:
      - "3000:3000"
    container_name: "sns-client"
  mysql:
    build: ../db
    restart: always
    volumes:
      - "../db/data:/var/lib/mysql/"
      - "../db/conf:/etc/mysql/conf.d"
      - "../db/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sns
      MYSQL_USER: kazuki
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    ports:
      - "13306:3306"
    container_name: "sns-db"
